Resources:
  DynamoDBSessionsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: sessionID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: sessionID
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.resourcePrefix}-sessions

  DynamoDBWorkspacesTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: teamID
          KeyType: HASH
        - AttributeName: userID
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: teamID
          AttributeType: S
        - AttributeName: userID
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.resourcePrefix}-workspaces

  DynamoDBSettingsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: identifier
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S
        - AttributeName: nextExecutionDate
          AttributeType: S
        - AttributeName: nextExecutionTimestamp
          AttributeType: N
      GlobalSecondaryIndexes: 
        - IndexName: nextExecutionDate
          KeySchema:
            - AttributeName: nextExecutionDate
              KeyType: HASH
            - AttributeName: nextExecutionTimestamp
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.resourcePrefix}-settings

  DynamoDBStandupsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      KeySchema:
        - AttributeName: identifier
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: identifier
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.resourcePrefix}-standups
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  SQSStartQueue:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: ${self:custom.resourcePrefix}-start