Resources:
  DynamoDBStandUpsTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain # TODO: uncomment when released
    Properties:
      KeySchema:
        - AttributeName: user_id
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.resourcePrefix}-standups
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  DynamoDBSettingsTable:
    Type: AWS::DynamoDB::Table
    # DeletionPolicy: Retain # TODO: uncomment when released
    Properties:
      KeySchema:
        - AttributeName: target_channel_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: target_channel_id
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName: ${self:custom.resourcePrefix}-settings

  StartLambdaFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Fn::GetAtt:
          - StartLambdaFunction
          - Arn
      Principal: events.amazonaws.com
