plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-plugin-typescript

service: daily-standup-bot

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_REGION, 'us-east-1'}
  environment:
    SERVERLESS_STAGE: ${self:custom.currentStage}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_REDIRECT_URI: ${env:SLACK_REDIRECT_URI}
    SESSION_SECRET: ${env:SESSION_SECRET}
    SESSION_DYNAMODB_TABLE: ${self:custom.resourcePrefix}-sessions
    WORKSPACE_DYNAMODB_TABLE: ${self:custom.resourcePrefix}-workspaces
    DYNAMODB_ENDPOINT: ${env:DYNAMODB_ENDPOINT}

custom:
  currentStage: ${opt:stage, self:provider.stage}
  resourcePrefix: ${self:service}-${self:custom.currentStage}

  # serverless-dynamodb-local settings
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true

functions:
  app:
    handler: src/handler.app
    events:
      # Bolt App
      - http:
          method: post
          path: /slack/events

      # OAuth Flow
      - http:
          method: get
          path: /slack/oauth
      - http:
          method: get
          path: /slack/oauth/callback

resources: ${file(resources.yml)}
