service: daily-standup-bot

frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:PutItem
    Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:custom.resourcePrefix}-standups

custom:
  currentStage: ${opt:stage, self:provider.stage}
  resourcePrefix: ${self:service}-${self:custom.currentStage}

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  hello:
    handler: bin/hello
    events:
      - http:
          path: hello
          method: get
  world:
    handler: bin/world
    events:
      - http:
          path: world
          method: get
  webhook:
    handler: bin/webhook
    events:
      - http:
          path: webhook
          method: post
    environment:
      STANDUPS_TABLE: ${self:custom.resourcePrefix}-standups

resources: ${file(resources.yml)}
