plugins:
  - serverless-offline
  - serverless-webpack

service: daily-standup-bot

provider:
  name: aws
  runtime: nodejs8.10
  region: ${env:AWS_REGION, 'us-east-1'}
  environment:
    SERVERLESS_STAGE: ${self:custom.currentStage}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_REDIRECT_URI: ${env:SLACK_REDIRECT_URI}

custom:
  currentStage: ${opt:stage, self:provider.stage}

functions:
  app:
    handler: handler.app
    events:
      # Bolt App
      - http:
          method: post
          path: /slack/events
      # OAuth Flow
      - http:
          method: get
          path: /slack/installation
      - http:
          method: get
          path: /slack/oauth
