name: Deploy with Serverless

on:
  push:
    branches: [migrate-to-bolt]

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v1

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - run: npm install

    - run: npx sls deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
        SLACK_CLIENT_ID: ${{ secrets.SLACK_CLIENT_ID }}
        SLACK_CLIENT_SECRET: ${{ secrets.SLACK_CLIENT_SECRET }}
        SLACK_REDIRECT_URI: ${{ secrets.SLACK_REDIRECT_URI_BASE }}/slack/oauth/callback
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
